version: '3.4'

services:
  movies:
    image: ${DOCKER_REGISTRY-}movies
    build:
      context: .
      dockerfile: Movies\Dockerfile

  frontend:
    build:
      context: Movies\ReactMovies\movie-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"